* 09 Reproducible Outputs and Handoff Files Stata Lab
* Purpose: create an analysis-ready handoff package from synthetic survey data,
* including datasets, a summary table, a derived codebook, a workflow log,
* and a handoff memo.
* Run this do-file from the repository root.
* Beginner note: if running interactively, run the setup block from version
* through log using as a block before running later lines. Do not run isolated
* lines that depend on local macros, imported data, or open logs.

version 17
clear all
set more off

* Confirm this do-file is being run from the repository root.
capture confirm file "README.md"
if _rc {
    display as error "README.md not found."
    display as error "Run this do-file from the repository root: the folder containing README.md, modules/, code/, and data/."
    exit 601
}

capture confirm file "modules/00-orientation/stata_lab.do"
if _rc {
    display as error "modules/00-orientation/stata_lab.do not found."
    display as error "Run this do-file from the repository root: the folder containing README.md, modules/, code/, and data/."
    exit 601
}

capture confirm file "code/stata/create-synthetic-data.do"
if _rc {
    display as error "code/stata/create-synthetic-data.do not found."
    display as error "Run this do-file from the repository root: the folder containing README.md, modules/, code/, and data/."
    exit 601
}

capture confirm file "data/synthetic/README.md"
if _rc {
    display as error "data/synthetic/README.md not found."
    display as error "Run this do-file from the repository root: the folder containing README.md, modules/, code/, and data/."
    exit 601
}

* Store project-relative paths in locals.
local source_csv "data/synthetic/synthetic_gss_like_person_2024.csv"
local analysis_dta "data/output/synthetic_gss_like_analysis_ready_stata.dta"
local analysis_csv "data/output/synthetic_gss_like_analysis_ready_stata.csv"
local analysis_xlsx "data/output/synthetic_gss_like_analysis_ready_stata.xlsx"
local summary_csv "data/output/module-09-stata-region-summary.csv"
local summary_xlsx "data/output/module-09-stata-region-summary.xlsx"
local codebook_md "data/output/module-09-stata-derived-codebook.md"
local handoff_memo "data/output/module-09-stata-handoff-memo.md"
local log_file "logs/module-09-stata-log.txt"

* Create output folders if they do not already exist.
capture mkdir "logs"
capture mkdir "data/output"

* Start a plain-text log for review.
capture log close
log using "logs/module-09-stata-log.txt", text replace

display as text "Module 09 Stata reproducible outputs log"
display as text "Source file: `source_csv'"

* Confirm the source file exists before doing any work.
confirm file "`source_csv'"

* Import the raw teaching file. The raw CSV remains unchanged.
import delimited using "`source_csv'", clear varnames(1) case(lower) bindquote(strict)
capture rename respondentid respondent_id
capture rename surveyyear year
capture rename survey_year year
capture rename raceethnicity race_ethnicity
capture rename maritalstatus marital_status
capture rename employmentstatus employment_status
capture rename householdincome household_income
capture rename selfratedhealth self_rated_health
capture rename physicalactivitydays physical_activity_days
capture rename surveyweight survey_weight
capture rename interviewmode interview_mode

count
local imported_rows = r(N)
local imported_vars = c(k)

display as text "Imported rows: `imported_rows'"
display as text "Imported variables: `imported_vars'"
describe

* Confirm required variables are present.
foreach var in respondent_id year age gender race_ethnicity education marital_status region employment_status hours_worked household_income self_rated_health smoking_status physical_activity_days survey_weight {
    confirm variable `var'
}

* Some CSV imports may guess numeric types differently across computers.
* Convert fields used with string-cleaning functions to string only if needed.
foreach var in gender race_ethnicity education marital_status region employment_status hours_worked household_income self_rated_health smoking_status physical_activity_days survey_weight {
    capture confirm numeric variable `var'
    if !_rc {
        tostring `var', replace force
    }
}

* Keep basic source metadata in the dataset.
notes _dta: Module 09 teaching output generated from synthetic_gss_like_person_2024.csv.
notes _dta: Generated by modules/09-reproducible-outputs/stata_lab.do.
notes _dta: Do not manually edit generated handoff outputs; update and rerun the do-file.

* Identify duplicate respondent-year rows before creating the handoff dataset.
bysort respondent_id year: generate duplicate_order = _n
generate duplicate_person_year = duplicate_order > 1
label variable duplicate_order "Order within respondent-year duplicate group"
label variable duplicate_person_year "Duplicate respondent-year row indicator"

* Clean and derive analysis variables.
generate age_clean = age
replace age_clean = . if inlist(age_clean, -9, 999)
label variable age_clean "Age in years after recoding special missing codes"
notes age_clean: -9 and 999 treated as missing before analytic sample restriction.

generate gender_text = lower(trim(gender))
replace gender_text = "" if inlist(gender_text, "-9", "prefer not to answer")
generate str20 gender_clean = ""
replace gender_clean = "Female" if gender_text == "female"
replace gender_clean = "Male" if gender_text == "male"
replace gender_clean = "Nonbinary" if gender_text == "nonbinary"
label variable gender_clean "Cleaned gender category"

generate race_ethnicity_clean = strproper(strtrim(race_ethnicity))
replace race_ethnicity_clean = "" if race_ethnicity_clean == "-9"
label variable race_ethnicity_clean "Cleaned race and ethnicity category"

generate education_clean = strproper(strtrim(education))
replace education_clean = "" if education_clean == "-9"
label variable education_clean "Cleaned education category"

generate marital_status_clean = strproper(strtrim(marital_status))
replace marital_status_clean = "" if marital_status_clean == "-9"
label variable marital_status_clean "Cleaned marital status category"

generate region_clean = strproper(strtrim(region))
replace region_clean = "" if region_clean == "-9"
label variable region_clean "Cleaned region category"

generate employment_status_clean = strproper(strtrim(employment_status))
replace employment_status_clean = "" if employment_status_clean == "-9"
label variable employment_status_clean "Cleaned employment status category"

generate hours_text = lower(trim(hours_worked))
replace hours_text = "" if inlist(hours_text, "-8", "-9", "n/a", "forty")
destring hours_text, generate(hours_worked_num)
label variable hours_worked_num "Usual hours worked per week as numeric"

generate income_text = lower(trim(household_income))
replace income_text = subinstr(income_text, "$", "", .)
replace income_text = subinstr(income_text, ",", "", .)
replace income_text = "" if inlist(income_text, "", "-8", "999999", "not asked")
destring income_text, generate(household_income_num)
label variable household_income_num "Household income as numeric dollars"

generate health_text = lower(trim(self_rated_health))
replace health_text = "" if inlist(health_text, "", "-9", "dk")
generate self_rated_health_ord = .
replace self_rated_health_ord = 1 if health_text == "poor"
replace self_rated_health_ord = 2 if health_text == "fair"
replace self_rated_health_ord = 3 if health_text == "good"
replace self_rated_health_ord = 4 if health_text == "very good"
replace self_rated_health_ord = 5 if health_text == "excellent"
label define health_lbl 1 "Poor" 2 "Fair" 3 "Good" 4 "Very good" 5 "Excellent"
label values self_rated_health_ord health_lbl
label variable self_rated_health_ord "Self-rated health ordinal scale"

generate smoking_status_clean = strproper(strtrim(smoking_status))
replace smoking_status_clean = "" if inlist(smoking_status_clean, "", "-9")
label variable smoking_status_clean "Cleaned smoking status category"

generate activity_text = lower(trim(physical_activity_days))
replace activity_text = "" if inlist(activity_text, "-9", "not asked", "eight")
destring activity_text, generate(physical_activity_days_num)
label variable physical_activity_days_num "Physical activity days per week as numeric"

generate weight_text = trim(survey_weight)
replace weight_text = subinstr(weight_text, ",", ".", .)
replace weight_text = "" if inlist(weight_text, "", "-9")
destring weight_text, generate(survey_weight_num)
label variable survey_weight_num "Positive survey weight as numeric"

* Create an explicit analytic sample flag before exporting the restricted file.
generate analytic_sample_flag = duplicate_order == 1 ///
    & !missing(age_clean) ///
    & age_clean >= 18 ///
    & age_clean <= 89 ///
    & gender_clean != "" ///
    & !missing(household_income_num) ///
    & !missing(self_rated_health_ord) ///
    & !missing(survey_weight_num) ///
    & survey_weight_num > 0
label variable analytic_sample_flag "Included in module 09 analysis-ready output"

* Validate cleaned values before export.
assert missing(age_clean) | (age_clean >= 18 & age_clean <= 89)
assert missing(physical_activity_days_num) | (physical_activity_days_num >= 0 & physical_activity_days_num <= 7)
assert missing(survey_weight_num) | survey_weight_num > 0

tabulate analytic_sample_flag, missing
tabulate gender_clean, missing
summarize age_clean hours_worked_num household_income_num self_rated_health_ord physical_activity_days_num survey_weight_num
codebook respondent_id year age_clean gender_clean region_clean household_income_num self_rated_health_ord survey_weight_num

tempfile cleaned_full analysis_ready region_summary
save `cleaned_full', replace

* Create the analysis-ready handoff dataset. The sample restriction is
* documented in the memo and codebook.
keep if analytic_sample_flag == 1
keep respondent_id year age_clean gender_clean race_ethnicity_clean education_clean marital_status_clean region_clean employment_status_clean hours_worked_num household_income_num self_rated_health_ord smoking_status_clean physical_activity_days_num survey_weight_num

rename age_clean age
rename gender_clean gender
rename race_ethnicity_clean race_ethnicity
rename education_clean education
rename marital_status_clean marital_status
rename region_clean region
rename employment_status_clean employment_status
rename hours_worked_num hours_worked
rename household_income_num household_income
rename self_rated_health_ord self_rated_health
rename smoking_status_clean smoking_status
rename physical_activity_days_num physical_activity_days
rename survey_weight_num survey_weight

generate str45 source_file = "synthetic_gss_like_person_2024.csv"
label variable source_file "Source file used to create the handoff dataset"

isid respondent_id year
count
local analysis_rows = r(N)
local analysis_vars = c(k)

save `analysis_ready', replace
save "`analysis_dta'", replace
export delimited using "`analysis_csv'", replace
export excel using "`analysis_xlsx'", firstrow(variables) replace

* Create a simple descriptive output table.
preserve
collapse (count) n=respondent_id ///
    (mean) mean_age=age ///
    (mean) mean_household_income=household_income ///
    (mean) mean_survey_weight=survey_weight, by(region)
format mean_age %9.1f
format mean_household_income %12.0f
format mean_survey_weight %9.2f
sort region
save `region_summary', replace
export delimited using "`summary_csv'", replace
export excel using "`summary_xlsx'", firstrow(variables) replace
restore

* Write a derived codebook for the handoff variables.
capture file close cb
file open cb using "`codebook_md'", write replace text
file write cb "# Module 09 Stata Derived Codebook" _n _n
file write cb "| Variable | Description | Source or derivation |" _n
file write cb "| --- | --- | --- |" _n
file write cb "| respondent_id | Synthetic respondent identifier | Respondent ID; duplicate respondent-year rows removed from analysis-ready output |" _n
file write cb "| year | Survey year | Renamed from Survey Year during import |" _n
file write cb "| age | Age in years | -9 and 999 treated as missing before sample restriction |" _n
file write cb "| gender | Cleaned gender category | Capitalization and whitespace standardized; nonresponse excluded from analysis-ready output |" _n
file write cb "| race_ethnicity | Cleaned race and ethnicity category | Capitalization and whitespace standardized |" _n
file write cb "| education | Cleaned education category | Capitalization and whitespace standardized |" _n
file write cb "| marital_status | Cleaned marital status category | Capitalization and whitespace standardized |" _n
file write cb "| region | Cleaned region category | Capitalization and whitespace standardized |" _n
file write cb "| employment_status | Cleaned employment status category | Capitalization and whitespace standardized |" _n
file write cb "| hours_worked | Usual hours worked per week | -8, -9, N/A, and text value forty treated as missing |" _n
file write cb "| household_income | Household income in dollars | -8, 999999, Not asked, currency marks, and commas handled before numeric conversion |" _n
file write cb "| self_rated_health | Ordinal self-rated health | 1 Poor through 5 Excellent; DK and -9 treated as missing before sample restriction |" _n
file write cb "| smoking_status | Cleaned smoking status category | Blanks and -9 treated as missing |" _n
file write cb "| physical_activity_days | Physical activity days per week | -9, Not asked, and text value eight treated as missing |" _n
file write cb "| survey_weight | Positive survey weight | Blank, -9, and comma decimal formats handled before numeric conversion |" _n
file write cb "| source_file | Source file used to create handoff dataset | Constant value added for provenance |" _n
file close cb

* Write a short handoff memo in Markdown.
capture file close memo
file open memo using "`handoff_memo'", write replace text
file write memo "# Module 09 Stata Handoff Memo" _n _n
file write memo "## Purpose" _n
file write memo "This handoff package contains analysis-ready synthetic survey data and companion documentation generated from a scripted Stata workflow." _n _n
file write memo "## File Provenance" _n
file write memo "- Source file: `source_csv'." _n
file write memo "- Script: modules/09-reproducible-outputs/stata_lab.do." _n
file write memo "- Workflow log: `log_file'." _n _n
file write memo "## Generated Outputs" _n
file write memo "- Analysis-ready Stata file: `analysis_dta'." _n
file write memo "- Analysis-ready CSV: `analysis_csv'." _n
file write memo "- Analysis-ready Excel file: `analysis_xlsx'." _n
file write memo "- Region summary CSV: `summary_csv'." _n
file write memo "- Region summary Excel file: `summary_xlsx'." _n
file write memo "- Derived codebook: `codebook_md'." _n _n
file write memo "## Sample Construction" _n
file write memo "- Imported rows: `imported_rows'." _n
file write memo "- Analysis-ready rows: `analysis_rows'." _n
file write memo "- Analysis-ready output keeps rows with valid age, gender, income, self-rated health, positive survey weight, and no duplicate respondent-year key." _n _n
file write memo "## Known Limitations" _n
file write memo "- These data are synthetic and intended only for teaching." _n
file write memo "- Some raw records contain intentional teaching problems and are excluded from the analysis-ready output by the scripted sample flag." _n
file write memo "- CSV files do not preserve all metadata, so the derived codebook should travel with the dataset." _n _n
file write memo "## Reproducibility Note" _n
file write memo "Do not manually edit the generated output files. Update the do-file and rerun it if the handoff package needs to change." _n
file close memo

display as text "Reproducible output workflow complete."
display as text "Analysis-ready rows: `analysis_rows'"
display as text "Analysis-ready Stata file saved to `analysis_dta'"
display as text "Analysis-ready CSV saved to `analysis_csv'"
display as text "Derived codebook saved to `codebook_md'"
display as text "Handoff memo saved to `handoff_memo'"

log close
